[build]
  command = "mkdir -p public && npm install"
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/api/health"
  status = 200

[[redirects]]
  from = "/abonos/*"
  to = "/.netlify/functions/api/abonos/:splat"
  status = 200

[[redirects]]
  from = "/transacciones/*"
  to = "/.netlify/functions/api/transacciones/:splat"
  status = 200

[[redirects]]
  from = "/deuda-detalle"
  to = "/.netlify/functions/api/deuda-detalle"
  status = 200
